name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  setup:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Upgrade npm to match local lockfile
        run: |
          npm i -g npm@11.3.0
          npm --version
      - name: Install dependencies (root + all workspaces)
        run: npm ci --workspaces
      - name: Typecheck (server)
        run: npm --workspace server run typecheck
      - name: Lint (server)
        run: npm --workspace server run lint
      - name: Test (server)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm --workspace server run test


